export const ADD_FCARD = "ADD_FCARD";
export const UPDATE_FCARD = "UPDATE_FCARD";
export const DELETE_FCARD = "DELETE_FCARD";
export const FILTER_FCARDS = "FILTER_FCARDS";
export const INCREASE_TOTAL = "INCREASE_TOTAL";
export const DECREASE_TOTAL = "DECREASE_TOTAL";
export const SET_CURRENCY_RATES = "SET_CURRENCY_RATES";
